abbr gd 'git diff'
abbr gr 'git remote -vv'
abbr gl 'git log --graph --decorate --oneline'
abbr gs 'git status'
abbr gla 'git log --graph --decorate --oneline --branches --remotes'
abbr gf 'git fetch --all --prune --tags'
abbr gb 'git branch -vv'
abbr glp 'git log -p'
abbr clip 'xclip -sel clip'
abbr gc 'git clean -fxd'
abbr pbr 'planex-buildenv run'
